#!/bin/bash

get_seeded_random()
{
  seed="$1"
  openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt \
    </dev/zero 2>/dev/null
}

shuf -i1-10 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 6 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-100 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 8 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-5214 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-20000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 4 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-20000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-100000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 9 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-200000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-500000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-10 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 2 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-100 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-5214 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-20000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 10 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-20000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 2 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-100000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 9 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-200000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 2 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

shuf -i1-500000 --random-source=<(get_seeded_random 10) > case3.txt
sort -n case3.txt > linux_test_bucket.txt
./mysort case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "Pass" || echo "Fail"

sort -n special_case1.txt > linux_test_bucket.txt
./mysort special_case1.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP1B Pass" || echo "SP1B Fail"

sort -n special_case2.txt > linux_test_bucket.txt
./mysort special_case2.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP2B Pass" || echo "SP2B Fail"

sort -n special_case3.txt > linux_test_bucket.txt
./mysort special_case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=sense
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP3B Pass" || echo "SP3B Fail"

sort -n special_case1.txt > linux_test_bucket.txt
./mysort special_case1.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP1bucket Pass" || echo "SP1bucket Fail"

sort -n special_case2.txt > linux_test_bucket.txt
./mysort special_case2.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP2bucket Pass" || echo "SP2bucket Fail"

sort -n special_case3.txt > linux_test_bucket.txt
./mysort special_case3.txt -o test_bucket.txt -t 12 --alg=bucket --bar=pthread
cmp --silent test_bucket.txt linux_test_bucket.txt && echo "SP3bucket Pass" || echo "SP3bucket Fail"
