#!/bin/bash

get_seeded_random()
{
  seed="$1"
  openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt \
    </dev/zero 2>/dev/null
}

shuf -i1-10 --random-source=<(get_seeded_random 5) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-100 --random-source=<(get_seeded_random 5) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-1000 --random-source=<(get_seeded_random 5) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-5314 --random-source=<(get_seeded_random 500) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-20000 --random-source=<(get_seeded_random 795) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-100000 --random-source=<(get_seeded_random 5345) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-500000 --random-source=<(get_seeded_random 5090) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -i1-1350000 --random-source=<(get_seeded_random 5090) > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"

shuf -r -n 1304640 -i 0-1000 > case3.txt
sort -n case3.txt > soln3.txt
./mysort case3.txt -o your3.txt
cmp --silent your3.txt soln3.txt && echo "Pass" || echo "Fail"